spring.application.name=kageguard-backend
server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:kageguarddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Create tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Browser database viewer
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Fake packet generator (set to false to turn it off)
kageguard.simulator.enabled=true;